#!/usr/bin/env bash

set -euo pipefail

# use like this:
#
#    /entrypoint -b 0.0.0.0:8080
#

# make sure we have a correctly configured environment
[ -z "$APP_ROOT" ] && exit 1
cd "$APP_ROOT" || exit 1

# use arguments entirely from the caller and make no assumptions
exec tini -- "$VIRTUALENV"/bin/hypercorn "$APP_NAME".asgi:app "$@"
