name: Create Release

on:
  # only trigger this workflow manually
  workflow_dispatch:
    inputs:
      increment:
        description: "Set a field to increment."
        required: false
        default: ""
        type: choice
        options:
          - ""
          - MAJOR
          - MINOR
          - PATCH
      prerelease:
        description: "Set as a prerelease version."
        required: false
        default: ""
        type: choice
        options:
          - ""
          - alpha
          - beta
          - rc

jobs:
  tests:
    uses: ./.forgejo/workflows/tests.yaml
    secrets: inherit

  security:
    uses: ./.forgejo/workflows/security.yaml
    secrets: inherit

  bump_version:
    runs-on: ubuntu-latest

    # only run if the other jobs succeed
    needs:
      - tests
      - security

    permissions:
      contents: write

    steps:
      - name: Check out the code
        uses: https://data.forgejo.org/actions/checkout@v7
        with:
          ssh-key: "${{ secrets.DEPLOY_KEY }}"

      - name: Set up python
        uses: https://data.forgejo.org/actions/setup-python@v7
        with:
          python-version: "3.14.x"

      - name: Create changelog and bump version
        id: cz
        run: |
          pip install commitizen
          git config --global user.name "forgejo-action"
          git config --global user.email "noreply@lockaby.org"

          BUMP_ARGS=""
          if [ "${{ inputs.increment }}" != "" ]; then
            BUMP_ARGS="$BUMP_ARGS --increment ${{ inputs.increment }}"
          fi
          if [ "${{ inputs.prerelease }}" != "" ]; then
            BUMP_ARGS="$BUMP_ARGS --prerelease ${{ inputs.prerelease }}"
          fi

          cz bump $BUMP_ARGS

          NEW_VERSION=$(git describe --tags --abbrev=0)
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Push changelog updates
        run: |
          git push origin main --tags

      - name: Create release
        uses: https://github.com/softprops/action-gh-release@v3
        with:
          body_path: "changes.md"
          tag_name: "${{ steps.cz.outputs.version }}"

      - run: |
          echo "Bumped to version ${{ steps.cz.outputs.version }}"
