name: Security Scanning

on:
  workflow_call:
  schedule:
    - cron: "0 2 * * 1"

jobs:
  trivy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out the code
        uses: https://data.forgejo.org/actions/checkout@v6

      - name: Run trivy configuration checks
        run: |
          trivy config . --config=.trivy.yaml --ignorefile=.trivyignore

      - name: Run trivy filesystem checks
        run: |
          trivy filesystem . --config=.trivy.yaml --ignorefile=.trivyignore --no-progress
