name: Security Scanning

on:
  workflow_call:
  schedule:
    - cron: "0 2 * * 1"

jobs:
  trivy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out the code
        uses: actions/checkout@v6

      - name: Run trivy configuration checks
        run: |
          if [[ -f "/usr/local/bin/trivy" ]]; then
            trivy config . --config=.trivy.yaml --ignorefile=.trivyignore
          fi

      - name: Run trivy filesystem checks
        run: |
          if [[ -f "/usr/local/bin/trivy" ]]; then
            trivy filesystem . --config=.trivy.yaml --ignorefile=.trivyignore --no-progress
          fi
